config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:index, :show, :create, :edit, :update]
  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]

  end

  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in:2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully!!"
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully!!"
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end


  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    @books = Book.all
    if @book.save
      flash[:notice] = "You have created book successfully!!"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @book2 = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully!!"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully!!"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %>
    <% end %>
  </ul>
<% end %>

<main>
  <h1>Editing Book</h1>
  <%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
  <% end %>
  <%= link_to "Show", book_path(@book.id) %>|
  <%= link_to "Back", books_path %>
</main>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %>
    <% end %>
  </ul>
<% end %>
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
      <%= render '/common/userinfo&newbook', book: @book, user: @user %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class = "tabel table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag  book.user.get_profile_image(100,100) %>
              <% end %>
            </th>
            <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </th>
            <th>
              <%= book.body %>
            </th>
            <th>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class = "fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class = "fas fa-heart"></i>
                  <%= book.favorites.count %>
              <% end %>
            <% end %>
            </th>
            <th>
              コメント数:<%= book.book_comments.count %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %>
    <% end %>
  </ul>
<% end %>
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
      <%= render '/common/userinfo&newbook', book: @book2, user: @book.user%>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class = "table table-striped">
        <tr>
          <th>
            <%= link_to user_path(@book.user_id) do %>
            <%= image_tag @book.get_image %>
            <%= @book.user.name %>
            <% end %>
          </th>
          <th>
            <%= link_to book_path(@book.id) do %>
            <%= @book.title %>
            <% end %>
          </th>
          <th>
            <%= @book.body %>
          </th>
          <th>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book), method: :delete do %>
                ♥<%= @book.favorites.count %>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book), method: :post do %>
                <i class = "fas fa-heart"></i>
                <%= @book.favorites.count %>
              <% end %>
            <% end %>
          </th>
          <th>
            コメント数:<%= @book.book_comments.count %>
          </th>
          <% if @book.user == current_user %>
          <th>
            <%= link_to "Edit", edit_book_path(@book), class:"btn btn-lg btn-block btn-info mt-4 " %>
          </th>
          <th>
            <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-lg btn-block btn-info mt-4 " %>
          </th>
          <% end %>
        </tr>
      </table>

      <div class = "row">
      <% @book.book_comments.each do |book_comment| %>
        <div class = "col-md-2">
          <%= link_to user_path(book_comment.user_id) do %>
          <p><%= image_tag book_comment.user.get_profile_image(100,100) %></p>
          <%= book_comment.user.name %>
          <% end %>
        </div>
        <div class = "col-md-2">
          <%= book_comment.comment %>
        </div>
        <div class = "col-md-2">
          <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-lg btn-block btn-info mt-4" %>
          <% end %>
        </div>
      <% end %>
      </div>

      <div class = "row">
        <%= form_with model: [@book, @book_comment] do |f| %>
        <%= f.text_area :comment, rows: '5' %>
        <%= f.submit "送信" %>
        <% end %>
      </div>



    </div>

  </div>
</div>

app/views/common/_userinfo&newbook.html.erb
  <h2>User info</h2>
  <div>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class = "table table-striped">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <% if user.id == current_user.id %>
      <%= link_to  edit_user_path(user.id) do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    <% else %>
      <%= link_to  edit_user_path(user.id) do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  </div>

  <h2>New book</h2>
  <%= form_with model: book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/homes/about.html.erb
<h1>Welcom to <strong class = "fas fa-book">Bookers!</strong></h1>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<main>
    <h1>welcome to
    <strong class = "fas fa-book">Bookers</strong>!!
    </h1>
    <p>
      In <strong class = "fas fa-book">Bookers,</strong><br>
      you can share and exchange your opinion, inpressions, and emotions<br>
      about various books!
    </p>
    <%= link_to 'Log in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

      <script src="https://kit.fontawesome.com/32d9c33367.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <div class="navbar nabbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: 'nav-link' do %>
                   <i class='fas fa-home'></i>
                   home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link' do %>
                    <i class='fas fa-users'></i>
                    users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: 'nav-link' do %>
                    <i class='fas fa-book-open'></i>
                    books
                  <% end %>
                </li>
                <li>
                  <%= link_to  destroy_user_session_path, method: :delete, class: 'nav-link' do %>
                    <i class='fas fa-sign-out-alt'></i>
                    logout
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: 'nav-link' do %>
                   <i class='fas fa-home'></i>
                   home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link' do %>
                    <i class='fas fa-link'></i>
                    about
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link' do %>
                    <i class='fas fa-user-plus'></i>
                    sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to  user_session_path, class: 'nav-link' do %>
                    <i class='fas fa-sign-in-alt'></i>
                    login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>

    <footer>
      <p>CopyRight Infratop.inc</p>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
  <label for="inputName">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroductuon", placeholder:"紹介"%>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
      <%= render '/common/userinfo&newbook', book: @book, user: @user %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class = "table table-striped">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <th>
              <%= image_tag user.get_profile_image(50,50) %>
            </th>
            <th>
              <%= user.name %>
            </th>
            <th>
              <%= link_to "Show", user_path(user.id) %>
            </th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %>
    <% end %>
  </ul>
<% end %>
<div class = "container">
  <div class = "row">
    <div class = "col-md-3">
      <%= render '/common/userinfo&newbook', book: @book, user: @user %>
    </div>

    <div class = "col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class = "table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <th>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag book.get_image %>
                <%= @user.name %>
              <% end %>
            </th>
            <th>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </th>
            <th>
              <%= book.body %>
            </th>
            <th>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class = "fas fa-heart"></i>
                  <%= book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class = "fas fa-heart"></i>
                  <%= book.favorites.count %>
              <% end %>
            <% end %>
            </th>
            <th>
              <%= link_to "コメント数:#{book.book_comments.count}", book_path(book.id) %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>